openapi: "3.0.1"
info:
  title: Business service API
  description: API with logic business
  version: 1.0.0
servers:
  - url: http://localhost:8585
    description: local server
paths:
  /api/business/product:
    post:
      summary: Create new Product
      operationId: createProduct
      requestBody:
        description: Request to create new product.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductRQ"
      responses:
        '200':
          description: Success create
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateProductRS"
  /api/business/persons:
    post:
      summary: Add additional person as HOST or SIGN to product
      operationId: additionalPerson
      requestBody:
        description: Request to add a person as HOST or SIGN
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdditionalPersonRQ'
      responses:
        '200':
          description: Success add
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdditionalPersonRS'
  /api/business/movement:
    post:
      summary: Movement the account
      operationId: doMovement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementRQ'
      responses:
        '200':
          description: Success add
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementRS'

  /api/business/report:
    post:
      summary: Report of BALANCE or MOVEMENT
      operationId: buildReport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportRQ'
      responses:
        '200':
          description: Success of build report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportRS'

components:
  schemas:
    CreateProductRQ:
      type: object
      properties:
        customerId:
          type: string
          description: customer id
        productType:
          type: string
          description: product type
        familyProduct:
          type: string
          description: family product could be ACTIVE or PASSIVe
        openAmount:
          type: number
          format: double
          description: amount to open accounts bank
        userBank:
          type: string
          description: userbank who create product

    CreateProductRS:
      type: object
      properties:
        result:
          type: boolean
        productId:
          type: string
          description: indicate product id of new product

        message:
          type: string
          description: indicate some message in case cannot create product

    AdditionalPersonRQ:
      type: object
      properties:
        customerId:
          type: string
          description: customer id
        typeAdditional:
          type: string
          description: additional type to add could be HOST (titular) or SIGN (firmantes autorizados)
        productId:
          type: string
          description: product id to assign
        fullName:
          type: string
          description: full name of additional person
        identificationNum:
          type: string
          description: identification number of additional person
        identificationType:
          type: string
          description: identification type of additional person
        email:
          type: string
          description: email of additional person
        phone:
          type: string
          description: phone of additional person

    AdditionalPersonRS:
      type: object
      properties:
        result:
          type: boolean
          description: result of to addition

    MovementRQ:
      type: object
      properties:
        customerId:
          type: string
          description: customerId
        productId:
          type: string
          description: productId
        movementType:
          type: string
          description:  type of movement DEPOSIT , WITHDRAWAL, TRANSFER
        accountNumberToTransfer:
          type: string
          description:  account number of passive product
        amount:
          type: number
          format: double
          description: amount of movement
    MovementRS:
      type: object
      properties:
        result:
          type: string
          description: result
        message:
          type: string
          description: obeservations

    ReportRQ:
      type: object
      properties:
        typeReport:
          type: string
          description: type report as BALANCE or MOVEMENT
        customerId:
          type: string
          description: customer id
        productId:
          type: string
          description: product id in case typereport is MOVEMENT

    ReportRS:
      type: object
      properties:
        typeReport:
          type: string
          description: type report as BALANCE or MOVEMENT
        customerId:
          type: string
          description: customer id
        dateToday:
          type: string
          format: date
          description: date today
        products:
          type: array
          description: list of products
          items:
            $ref: '#/components/schemas/ProductReportbean'

    ProductReportbean:
      type: object
      properties:
        productId:
          type: string
          description: type report as BALANCE or MOVEMENT
        customerId:
          type: string
          description: customer id
        productType:
          type: string
          description: product type
        familyType:
          type: string
          description:  family type of product PASSIVE or ACTIVE
        balance:
          type: number
          format: double
          description:  amount total of balance of passive product
        accountNumber:
          type: string
          description: account number of PASSIVE product
        creditCardNumber:
          type: string
          description: credit card number of ACTIVE product
        creditLimitTotal:
          type: number
          format: double
          description: credit limit of CC( credit card)
        creditUser:
          type: number
          format: double
          description: credit userd of CC
        creditEnabled:
          type: number
          format: double
          description: amount enabled to consume in case CC
