openapi: "3.0.1"
info:
  title: Business service API
  description: API with logic business
  version: 1.0.0
servers:
  - url: http://localhost:8585
    description: local server
paths:
  /api/business/products:
    post:
      summary: Create new Product
      operationId: createProduct
      requestBody:
        description: Request to create new product.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductRQ"
      responses:
        '200':
          description: Success create
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateProductRS"
  /api/business/persons:
    post:
      summary: Add additional person as HOST or SIGN to product
      operationId: additionalPerson
      requestBody:
        description: Request to add a person as HOST or SIGN
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdditionalPersonRQ'
      responses:
        '200':
          description: Success add
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdditionalPersonRS'
  /api/business/transactions:
    post:
      summary: Movement the account
      operationId: doMovement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementRQ'
      responses:
        '200':
          description: Success add
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementRS'

  /api/business/reports:
    post:
      summary: Report of BALANCE or MOVEMENT
      operationId: buildReport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReportRQ'
      responses:
        '200':
          description: Success of build report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportRS'
  /api/business/customers:
    post:
      summary: Create , update or delete customer
      operationId: managementCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManagementCustomerRQ'
      responses:
        '200':
          description: Customer created successfull
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManagementCustomerRS'
  /api/business/cards:
    post:
      summary: Update product PASSIVE with plastic card
      operationId: createCard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCardRQ'
      responses:
        '200':
          description: Create plastic card DEBIT associated to passive account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCardRS'
  /api/business/productTypes:
    post:
      summary: create new product type in the bank
      operationId: createProductType
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductTypeRQ'
      responses:
        '200':
          description: Success create new product type in the bank
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductTypeRS'



components:
  schemas:
    CreateProductRQ:
      type: object
      properties:
        customerId:
          type: string
          description: customer id
        productType:
          type: string
          description: product type
        familyProduct:
          type: string
          description: family product could be ACTIVE or PASSIVe
        openAmount:
          type: number
          format: double
          description: amount to open accounts bank
        userBank:
          type: string
          description: userbank who create product

    CreateProductRS:
      type: object
      properties:
        result:
          type: boolean
        productId:
          type: string
          description: indicate product id of new product

        message:
          type: string
          description: indicate some message in case cannot create product

    AdditionalPersonRQ:
      type: object
      properties:
        customerId:
          type: string
          description: customer id
        typeAdditional:
          type: string
          description: additional type to add could be HOST (titular) or SIGN (firmantes autorizados)
        productId:
          type: string
          description: product id to assign
        fullName:
          type: string
          description: full name of additional person
        identificationNum:
          type: string
          description: identification number of additional person
        identificationType:
          type: string
          description: identification type of additional person
        email:
          type: string
          description: email of additional person
        phone:
          type: string
          description: phone of additional person

    AdditionalPersonRS:
      type: object
      properties:
        result:
          type: boolean
          description: result of to addition

    MovementRQ:
      type: object
      properties:
        customerId:
          type: string
          description: customerId
        productId:
          type: string
          description: productId
        movementType:
          type: string
          description:  type of movement DEPOSIT , WITHDRAWAL, TRANSFER
        accountNumberToTransfer:
          type: string
          description:  account number of passive product
        amount:
          type: number
          format: double
          description: amount of movement
    MovementRS:
      type: object
      properties:
        result:
          type: string
          description: result
        message:
          type: string
          description: obeservations

    ReportRQ:
      type: object
      properties:
        typeReport:
          type: string
          description: type report MOVEMENT_BY_PRODUCT (para ver los moviemintos de un producto) - BALANCE_BY_CUSTOMER (ver los saldos de  todos los productos de un cliente) - COMMISSION (comisiones por periodo de tiempo de un producto) - PLASTI_CARD ( reporte con los últimos 10 movimientos de la tarjeta de débito y de crédito.)
        customerId:
          type: string
          description: customer id
        productId:
          type: string
          description: product id in case typereport is MOVEMENT
        plasticCardId:
          type: string
        dateFrom:
          type: string
          format: date
        dateTo:
          type: string
          format: date

    ReportRS:
      type: object
      properties:
        message:
          type: string
        typeReport:
          type: string
          description: type report as BALANCE or MOVEMENT, COMMISSION
        customerId:
          type: string
          description: customer id
        dateToday:
          type: string
          format: date
          description: date today
        dateFrom:
          type: string
          format: date
          description: date to COMMISSION
        dateTo:
          type: string
          format: date
          description: date to COMMISSION
        products:
          type: array
          description: list of products
          items:
            $ref: '#/components/schemas/ProductReportbean'
        resumeMovement:
          $ref: '#/components/schemas/ResumeMovement'

    ProductReportbean:
      type: object
      properties:
        productId:
          type: string
          description: type report as BALANCE or MOVEMENT
        customerId:
          type: string
          description: customer id
        productType:
          type: string
          description: product type
        familyType:
          type: string
          description:  family type of product PASSIVE or ACTIVE
        totalAmountPassiveProduct:
          type: number
          format: double
          description:  amount total of balance of passive product
        accountNumber:
          type: string
          description: account number of PASSIVE product
        creditCardNumber:
          type: string
          description: credit card number of ACTIVE product
        creditLimitTotal:
          type: number
          format: double
          description: credit limit of CC( credit card)
        creditUsed:
          type: number
          format: double
          description: credit userd of CC
        creditEnabled:
          type: number
          format: double
          description: amount enabled to consume in case CC
        averageBalanceOfMonth:
          type: number
          format: double
          description: saldo promedio del mes


    MovementReportbean:
      type: object
      properties:

        movementType:
          type: string
          description:  movement type as DEPOSIT or WITHDRAWAL
        amount:
          type: number
          format: double
          description: amount of the movement
        commissionAmount:
          type: number
          format: double
          description: commission amount of movement
        dateOfMovement:
          type: string
          format: date
          description: date of movement

    ManagementCustomerRQ:
      type: object
      properties:
        action:
          type: string
          description: action CREATE, UPDATE or DELETE
        name:
          type: string
          description: customer name
        lastName:
          type: string
          description: customer lastName
        typeClient:
          type: string
          description: indicate customer type as P (Personal), B (Business), V(Personal VIP), M(Business Mype)
        phone:
          type: string
          description: customer phone
        email:
          type: string
          description: customer email
        identificationType:
          type: string
          description: customer identification type
        numIdentification:
          type: string
          description: customer identification number
        createdBy:
          type: string
          description: bank user who create customer

    ManagementCustomerRS:
      type: object
      properties:
        result:
          type: boolean
        message:
          type: string
          description: observations about creation
    ResumeMovement:
      type: object
      properties:
        productId:
          type: string
        productType:
          type: string
        totalAmountDeposit:
          type: number
          format: double
        totalAmountWithdraw:
          type: number
          format: double
        totalAmountCommission:
          type: number
          format: double
        totalAmountPayments:
          type: number
          format: double
        totalAmountConsume:
          type: number
          format: double
        movements:
          type: array
          description: list of movements for reportType MOVEMENT
          items:
            $ref: '#/components/schemas/MovementReportbean'
    CreateCardRQ:
      type: object
      properties:
        productIdToAssociate:
          type: string
          description: customer name
        cardId:
          type: string
        actionToAssociate:
          type: string
          description: ALL_ACCOUNTS, CREATE_DEBIT_CARD
        customerId:
          type: string

    CreateCardRS:
      type: object
      properties:
        productIdAssociated:
          type: string
          description: customer name
        productsIdAssociated:
          type: array
          items:
            type: string
            description: list products id associated
        cardId:
          type: string
          description: card id
        typeCard:
          type: string
          description: type card
        cardNumber:
          type: string
          description: card number
        expirationDate:
          type: string
          description: expiration date
    ProductTypeRQ:
      type: object
      properties:
        code:
          type: string
          description: code to new product
        description:
          type: string
          description: description of this product
        familyType:
          type: string
          description: family type ACTIVE or PASSIVE
        isFreeMaintenanceCommission:
          type: boolean
          description: true if is free to apply commission per maintenance
        isFreeNumberMovement:
          type: boolean
          description: true if free number of movement per months
        isFreeCommissionPerMovement:
          type: boolean
          description: true if free of commission movement
        maxMovementPerMonth:
          type: number
          format: int64
          description: indicate maxime movement per month
        dateToUniqueMovement:
          type: string
          description: indicate date when permit only one movement per month
        maintenanceCommission:
          type: number
          format: double
          description: indicate commission amount of maintenance
        movementCommission:
          type: number
          format: double
          description: indicate commision amount for movement
    ProductTypeRS:
      type: object
      properties:
        status:
          type: string
          description: status of creation
        code:
          type: string
          description: code to new product
        description:
          type: string
          description: description of this product
        familyType:
          type: string
          description: family type ACTIVE or PASSIVE
        isFreeMaintenanceCommission:
          type: boolean
          description: true if is free to apply commission per maintenance
        isFreeNumberMovement:
          type: boolean
          description: true if free number of movement per months
        isFreeCommissionPerMovement:
          type: boolean
          description: true if free of commission movement
        maxMovementPerMonth:
          type: number
          format: int64
          description: indicate maxime movement per month
        dateToUniqueMovement:
          type: string
          description: indicate date when permit only one movement per month
        maintenanceCommission:
          type: number
          format: double
          description: indicate commission amount of maintenance
        movementCommission:
          type: number
          format: double
          description: indicate commision amount for movement